import Banner from "@/components/Banner";
import Head from "next/head";
import Image from "next/image";
import style from "../styles/Home.module.css";
import Card from "../components/Card";
import { fetchCoffeStores } from "../../lib/coffe-stores";
import useTrackLocation from "@/hooks/useTrackLocation";
import { useContext, useEffect, useState } from "react";
import { storeContext } from "@/context/store-context";
import ACTION_TYPES from "@/context/action";

const Home = (props) => {
  const { state, dispatch } = useContext(storeContext);
  const { coffeeStores, latLong } = state;

  // const [coffeeStores, setCoffeeStores] = useState([]);
  const [error, setError] = useState("");
  const { handleTrackLocation, errorMsg, loading } = useTrackLocation();
  const handleClick = () => {
    handleTrackLocation();
  };

  useEffect(() => {
    const fetchData = async () => {
      if (latLong) {
        try {
          const coffeeStores = await fetchCoffeStores(latLong, 9);
          dispatch({
            type: ACTION_TYPES.SET_COFFEE_STORES,
            payload: { coffeeStores },
          });
        } catch (error) {
          setError(error);
          console.log(error.message);
        }
      }
    };
    fetchData();
  }, [latLong]);

  return (
    <div className={style.container}>
      <Head>
        <title>Coffe Corner App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <Banner
          buttonText={loading ? "Locating...." : "View stores nearby"}
          handleClick={handleClick}
        />
        {errorMsg && (
          <p>
            Something went wrong: <b>{errorMsg}</b>
          </p>
        )}
        {error && (
          <p>
            Something went wrong: <b>{error}</b>
          </p>
        )}
        <div className={style.heroImage}>
          <Image
            src="/static/hero-image.png"
            height={400}
            width={700}
            alt="hero-image"
          />
          {coffeeStores.length > 0 && (
            <div className={style.sectionWrapper}>
              <h2 className={style.heading2}>Stores mear me</h2>
              <div className={style.cardLayout}>
                {coffeeStores.map((item) => {
                  return (
                    <Card
                      href={`${item.id}`}
                      imgUrl={
                        item.imgUrl ||
                        "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                      }
                      name={item.name}
                      key={item.id}
                    />
                  );
                })}
              </div>
            </div>
          )}
          {props.coffeeStores.length > 0 && (
            <div className={style.sectionWrapper}>
              <h2 className={style.heading2}>Pattukkottai stores</h2>
              <div className={style.cardLayout}>
                {props.coffeeStores.map((item) => {
                  return (
                    <Card
                      href={`${item.id}`}
                      imgUrl={
                        item.imgUrl ||
                        "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                      }
                      name={item.name}
                      key={item.id}
                    />
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export async function getStaticProps(context) {
  const coffeeStores = await fetchCoffeStores();
  return {
    props: {
      coffeeStores,
    },
  };
}

export default Home;
